### PR TITLE
Improvements to federation with Page, Article, and Document objects

### PR DESCRIPTION
**Pull request by ch0ccyra1n**
This pull request improves the federation code with respect to `Page`, `Article`, and `Document` objects, for example Lemmy Posts. This essentially solves #1 .

Displaying the titles made most sense to me by giving them the exact same behavior as a content warning, which looks rather nice:
image

One issue I encountered was that posts with no `content` wouldn't federate. This was solved by having any object without `content` present simply a link to the original post behind the same title content warning:
image

### CODE REVIEW

**Comment by TheEssem** [comment]
Not sure that I'm a fan of titles as content warnings, especially since that could cause conflicts if the original post has one. Firefish seems to add the title to the post content as a header (example: https://lethallava.land/notes/9iblalgsl13gag6d), maybe something similar can be done here?

As for posts without content but a link (like the second screenshot above), maybe use that link instead?

**Comment by Sqaaakoi** [comment]
> Not sure that I'm a fan of titles as content warnings, especially since that could cause conflicts if the original post has one. Firefish seems to add the title to the post content as a header (example: https://lethallava.land/notes/9iblalgsl13gag6d), maybe something similar can be done here?
> 
> As for posts without content but a link (like the second screenshot above), maybe use that link instead?

Content warnings are already used as titles across all fedi software as far as I've noticed, so I'd say that the field is being used appropriately here.
The "content warning" field needs to be relabeled and have some other marker that would indicate the title is a warning?
I've discussed this before and it's been controversial what people would be marking as warnings tbh. A boolean field isn't the way to go here.
Also, obviously this would be unrealistic to federate with in the current state of the fediverse, where everyone is on vanilla Mastodon instances that lack a lot of features

**Comment by ch0ccyra1n** [comment]
I'm thinking that Essem's idea makes a lot of sense. Apologies for the late reply. I'll be making some changes and testing it locally before updating the branch

**Comment by ch0ccyra1n** [comment]
So turns out this pull request is hella unstable lmao

**Comment by ch0ccyra1n** [comment]
For now I'm going to close this pull request because I'd probably want to redo this right at some point in the future.

**Pull request closed without merging**
